### PR TITLE
Fixes rubocop offenses

### PR DESCRIPTION
**Pull request by athompson-r7**
This commit fixes rubocop offenses that appear to be introduced with new
versions or rubocop

### CODE REVIEW

**Comment by jmanero-r7** [comment]
:+1: legit seems legit

**Comment by athompson-r7** [comment]
Thanks @jmanero-r7

**Comment by dgreene-r7** [comment]
Rubocop gives 3 more violations
```
Offenses:

lib/convection/dsl/helpers.rb:48:14: C: Use 2 (not 1) spaces for indenting an expression spanning multiple lines.
             .reject(&:empty?)
             ^^^^^^^
lib/convection/dsl/helpers.rb:49:14: C: Use 2 (not 1) spaces for indenting an expression spanning multiple lines.
             .reduce('') { |a, e| (e.length == 1 && !a.empty?) ? a + "_#{e}" : a + e }
             ^^^^^^^
lib/convection/dsl/helpers.rb:50:14: C: Use 2 (not 1) spaces for indenting an expression spanning multiple lines.
             .downcase
             ^^^^^^^^^
```

**Comment by athompson-r7** [comment]
I think the rules changed from the version in your lockfile and the latest(which is what travis-ci uses).

**Pull request merged**
