### PR TITLE
Print out error message correctly when there is one

### PR DESCRIPTION
**Pull request by rdickey-r7**
# Description
Commit a7c43b71c7f93c9250877155cae9840e52c3db4a broke error message printing by trying to print a variable that doesn't exist.  This fixes that glitch.

# Motivation and Context

# Usage Examples

# Testing Steps

# Post-merge Steps

### CODE REVIEW

**Comment by erran-r7** [comment]
@rdickey-r7 Ah crap, think there may be a bigger issue here. I think I changed that call because there was a undefined method error for some cases. :person_frowning:

**Comment by rdickey-r7** [comment]
@erran-r7 Either way, error_message is wrong.  I think you could have solved the problem that you were trying to solve with only the RuntimeError.new line, and not changing error.message to error_message.  So I think this is ok now (at least, it works for me)

**Comment by erran-r7** [comment]
Think this will break one of converge or diff but fix the other (whichever you were having an issue with). I'll check this out now. Sorry got caught up with other stiffness.

**Comment by erran-r7** [comment]
@rdickey-r7 never mind, the commit from myself *with* your changes resolves #227. The casting is done in the case that `error` is a string so `error.message` will give the string error message. I believe there was a bad rebase before merging that PR. Just validated your changes. 👍 🎉 Thanks again!

**Pull request merged**
