### PR TITLE
Resolve violations introduced by pulling in RuboCop v0.40.0

### PR DESCRIPTION
**Pull request by erran-r7**
@athompson-r7 @fmitchell-r7 @jmanero-r7 @simonirwin-r7 @eciramella-r7 Looks like our version constraint on RuboCop is too light since this is the second time I've seen RuboCop release a new version and existing files (which passed linting) start failing the TravisCI build.

This resolves the 15 violations that started failing one of my PRs.

### CODE REVIEW

**Comment by athompson-r7** [comment]
@erran-r7 out of curiousity what was the version bump?  Should be explicit with this version?

**Comment by erran-r7** [comment]
LOL. Didn't re-run RuboCop I introduced a few failures myself. 😅 one second.

**Comment by erran-r7** [comment]
> LOL. Didn't re-run RuboCop I introduced a few failures myself. 😅 one second.

Fixed in 1834960.

**Comment by erran-r7** [comment]
> @erran-r7 out of curiousity what was the version bump? Should be explicit with this version?

The version bump happened yesterday when `0.40.0` was released:
> 0.40.0 - May 9, 2016 (251 KB)

We currently specify `~> 0.34` in our Gemfile. We can make that more strict to include only patch version bumps or lock to `0.40.0` in this PR.

**Comment by athompson-r7** [comment]
> We currently specify ~> 0.34 in our Gemfile. We can make that more strict to include only patch version bumps or lock to 0.40.0 in this PR.

I just opened #124 to address this.

**Comment by athompson-r7** [comment]
LGTM :shipit:

**Pull request merged**
