### PR TITLE
issue-74 Redoing the description and summary.

### PR DESCRIPTION
**Pull request by eciramella-r7**
Consuming the entire readme.md made a mess out of rubygems.org.

Trying to clean it up.

### CODE REVIEW

**Comment by fmitchell-r7** [comment]
:+1: Looks good to me.

**Comment by athompson-r7** [comment]
LGTM

**Comment by fmitchell-r7** [comment]
We can probably remove the `SUMMARY` and `DESCRIPTION` from version.rb now.
https://github.com/rapid7/convection/blob/v0.2/lib/convection/version.rb#L4-L5

**Comment by eciramella-r7** [comment]
@fmitchell-r7 Updated the version.rb file per your comments.

**Comment by bturner-r7** [comment]
:+1:

**Comment by erran-r7** [comment]
Fixes #74.

**Pull request merged**
