### PR TITLE
Support stack life cycle tasks (#114 and #119)

### PR DESCRIPTION
**Pull request by erran-r7**
See also #114 (original issue) and #119 (accidentally merged/pushed a merge from an incorrect base branch).

### CODE REVIEW

**Comment by erran-r7** [comment]
As I'm doing some testing internally I've noticed: the lack of output for tasks is pretty confusing.

**Comment by simonirwin-r7** [comment]
Think this looks good.

**Comment by erran-r7** [comment]
Looks like a new version of RuboCop pulled in by TravisCI started causing failures here. See https://github.com/rapid7/convection/pull/123 for the resolved violations (nothing in this PR is in violation currently).

**Comment by erran-r7** [comment]
@athompson-r7 @jmanero-r7 Any additional feedback here? Does it make sense to merge this feature into the `v0.2` branch? Should we create a new `v0.3` branch/version for it since it is a pretty large change? I'm not sure when it'd make sense to start creating a `v1.0.0.pre.x` version to start iterating on.

**Pull request merged**
